'use strict';
const assert=require('assert');
const R=require('../../js/engines/recall-engine.js');
const G=require('../../js/engines/grading-engine.js');
const classify=(u,e,a)=>G.classifyDetailed(u,e,a);
assert.equal(R.memoryTier('지식·이해').key,'exact');
assert.equal(R.memoryTier('과정·기능').key,'exact');
assert.equal(R.memoryTier('성취기준').key,'exact');
assert.equal(R.memoryTier('성취기준 해설').key,'coreplus');
assert.equal(R.memoryTier('평가 방법','teaching-evaluation').key,'keyword');
assert.deepEqual(R.splitAchievement('[9정03-05] 데이터를 순차적으로 저장한다.'),{code:'[9정03-05]',body:'데이터를 순차적으로 저장한다.'});
const expected=['문제 추상화','알고리즘 표현 방법','순차적인 데이터 저장'];
let r=R.matchRecallList(['알고리즘 표현 방법','문제 추상화','순차적인 데이터 저장'],expected,classify);
assert.equal(r.contentExact,true);
assert.equal(r.orderCorrect,false);
assert.equal(R.sectionStatus(r),'near');
r=R.matchRecallList(['문제 추상화','','순차적인 데이터 저장'],expected,classify);
assert.equal(r.missing.length,1);
assert.equal(r.missing[0].value,'알고리즘 표현 방법');
assert.equal(R.sectionStatus(r),'unknown');
r=R.matchRecallList(['문제 추상화','엉뚱한 답','순차적인 데이터 저장'],expected,classify);
assert.equal(R.sectionStatus(r),'wrong');

assert.deepEqual(R.parseFreeRecallText('1. 문제 추상화\n- 알고리즘 표현 방법\n\n• 순차적인 데이터 저장'),['문제 추상화','알고리즘 표현 방법','순차적인 데이터 저장']);
assert.equal(R.recallMasteryStage({correctStreak:0}).key,'new');
assert.equal(R.recallMasteryStage({correctStreak:1}).key,'learned');
assert.equal(R.recallMasteryStage({correctStreak:2}).key,'stabilizing');
assert.equal(R.recallMasteryStage({correctStreak:3}).key,'stabilizing');
assert.equal(R.recallMasteryStage({correctStreak:4}).key,'mastered');
assert.equal(R.isRecallMastered({correctStreak:3}),false);
assert.equal(R.isRecallMastered({correctStreak:4}),true);
console.log('recall-engine: OK');
